//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AthenasSpider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BespokeOrders
    {
        public int BespokeId { get; set; }
        public int CId { get; set; }
        public Nullable<int> OId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> VarId { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
        public string CustomerImage { get; set; }
        public string Description { get; set; }
    
        public virtual Product Products { get; set; }
        public virtual Customer Customers { get; set; }
        public virtual Order Orders { get; set; }
    }
}
