//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AthenasSpider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdOrder
    {
        public int ItemID { get; set; }
        public int VarID { get; set; }
        public int OId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProdVariant ProdVariant { get; set; }
    }
}
